### ISSUE TITLE
ROBOTISのe-Manualの3.5 Bringupのエラーについて

### ISSUE THREAD

**Issue by Ayu0419** [HansRobo/rsj_ros_seminar_2024#1]
お世話になっております。
芝浦工業大学の三浦愛祐と申します。
ROBOTISのe-Manual通りにセットアップを進めているのですが、3.Quick Start Guideの3.5 Bringupの部分の「ros2 launch turtlebot3_bringup robot.launch.py」を実行したところ、エラーが出ます。
また、その次の項目のトピックリストとサーバーリストを表示させてみましたが、マニュアルの画像通りには表示されませんでした。
具体的には、以下の画像の通りです。
分かる範囲で色々と試してみましたが、エラーは解消されませんでした。
お手すきの際に回答をいただけると幸いです。
よろしくお願いいたします。

![3 5 1error](https://github.com/user-attachments/assets/da4ed0f8-e59a-420e-a5f1-d77a2d692e1c)

**Comment by HansRobo** [comment]
@Ayu0419 
お問い合わせありがとうございます。
画像の中のメッセージを確認しますと、/dev/ttyACM0のデバイスのセットアップに失敗しているようです。
以下に従って確認を行っていただけないでしょうか？

### 1. デバイスが存在するかの確認

以下のコマンドを実行して、エラーの発生しているデバイス「/dev/ttyACM0」が存在するか確認してください。

```bash
ls /dev 
```
存在しなければ、配線の接続などを確認してみてください。

また、「/dev/ttyACM1」などと末尾の数字が変わって存在する場合もあります。
この場合は、以下のようにデバイス名を指定して立ち上げてみてください。

```bash
ros2 launch turtlebot3_bringup robot.launch.py usb_port:=/dev/ttyACM1
```

### 2. デバイスの権限の設定

デバイスが存在しても必要な権限が付与されていないと、セットアップに失敗することがあります。
以下のコマンドで読み書き権限を設定した後、もう一度試してみてください。

```bash
sudo chmod a+rw /dev/ttyACM0
```

権限の設定状態は以下のコマンドで確認できます。
```bash
ls -l /dev/ttyACM0
```

**Comment by Ayu0419** [comment]
ご返信ありがとうございます。
色々試したところ、ROBOTIS e-manualのopenCRセットアップの0.4を飛ばして実行すると成功しました。
ご回答ありがとうございました。
